language: php

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.monorepo-split-cache

sudo: false

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0
    - SYMFONY_DEPRECATIONS_HELPER='weak_vendors'

jobs:
  include:
    # Lowest dependencies
    - php: 7.2
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

    # Highest dependencies
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2

    # Ignore the platform requirements for the upcoming PHP version
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-reqs'

    # Validate the split repos
    - stage: validate
      php: 7.2
      install: true
      script:
        - cd $TRAVIS_BUILD_DIR/calendar-bundle && run_split_tests
        - cd $TRAVIS_BUILD_DIR/core-bundle && run_split_tests
        - cd $TRAVIS_BUILD_DIR/faq-bundle && run_split_tests
        - cd $TRAVIS_BUILD_DIR/manager-bundle && run_split_tests
        - cd $TRAVIS_BUILD_DIR/news-bundle && run_split_tests

    # Split the monorepo
    - stage: split
      if: 'type = push AND (branch =~ /^(master|\d+\.\d+)$/ OR tag IS present)'
      php: 7.2
      install:
        - rm composer.json
        - composer require contao/monorepo-tools:dev-master --no-interaction --no-suggest
      script:
        - php vendor/bin/monorepo-tools split $TRAVIS_BRANCH --cache-dir $HOME/.monorepo-split-cache

    # Generate the coverage report
    - stage: coverage
      php: 7.2
      install:
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit -c calendar-bundle --coverage-clover=calendar-bundle.xml
        - php vendor/bin/phpunit -c core-bundle --exclude-group contao3 --coverage-clover=core-bundle.xml
        - php vendor/bin/phpunit -c faq-bundle --coverage-clover=faq-bundle.xml
        - php vendor/bin/phpunit -c manager-bundle --coverage-clover=manager-bundle.xml
        - php vendor/bin/phpunit -c news-bundle --coverage-clover=news-bundle.xml
      after_script:
        - php vendor/bin/php-coveralls -o coveralls-upload.json -x calendar-bundle.xml -x core-bundle.xml -x faq-bundle.xml -x manager-bundle.xml -x news-bundle.xml

  allow_failures:
    - php: nightly

install:
  - phpenv config-rm xdebug.ini || true
  # To be removed when this is resolved: https://github.com/composer/composer/issues/5355
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --no-interaction --no-suggest; fi
  - composer update $COMPOSER_FLAGS --no-interaction --no-suggest

script:
  - php vendor/bin/phpunit -c calendar-bundle
  - php vendor/bin/phpunit -c core-bundle
  - php vendor/bin/phpunit -c faq-bundle
  - php vendor/bin/phpunit -c installation-bundle
  - php vendor/bin/phpunit -c manager-bundle
  - php vendor/bin/phpunit -c news-bundle
  - if [[ -e vendor/bin/monorepo-tools ]]; then php vendor/bin/monorepo-tools composer-json --validate; fi

before_install:
  - |
    # Helper functions
    fix_dependencies () {
      php -r '
        $data = json_decode(file_get_contents(__DIR__."/composer.json"), true);
        $data["require"]["contao/manager-plugin"] = "^2.2";
        unset($data["require-dev"]["contao/monorepo-tools"]);
        file_put_contents(__DIR__."/composer.json", json_encode($data, JSON_UNESCAPED_SLASHES));
      '
    }
    run_split_tests () {
      php -r '
        $data = json_decode(file_get_contents(__DIR__."/composer.json"), true);
        if ("contao/core-bundle" !== $data["name"]) {
          $data["repositories"][0]["type"] = "path";
          $data["repositories"][0]["url"] = "../core-bundle";
        }
        if ("contao/installation-bundle" !== $data["name"]) {
          $data["repositories"][1]["type"] = "path";
          $data["repositories"][1]["url"] = "../installation-bundle";
        }
        file_put_contents(__DIR__."/composer.json", json_encode($data, JSON_UNESCAPED_SLASHES));
      '
      composer update --no-interaction --no-suggest
      php vendor/bin/phpunit --colors=always
    }
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]] || [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then fix_dependencies; fi
